### PR TITLE
Creates API endpoints for Events

### LINKED ISSUE #14: GET Event Endpoint
**Description**
Your task is to create a GET API endpoint that will retrieve all events and be able to get individual events.

**Acceptance Criteria**
API endpoints must be functioning and working with MongoDB.

Steps:
- Use mongoose to connect Schema and get users, similar to bootcamp.
- Getting All Events `/api/events`
- Getting Individual Event `/api/events/[eventId]`

### PR DESCRIPTION
**Pull request by SilveerDusk**
## Developer: Jason Jelincic

Closes #14 and #15

### Pull Request Summary

Creates all API endpoints for events (GET, POST, PATCH, DELETE)

### Modifications

api/events : 
    Get request for all events
    Post request to post a event
api/events/[eventId] : 
    Get request for a single event
    Delete request to delete an event
    Patch request to update an event

### Testing Considerations

Need help gaining access to Atlas so I can do proper testing.

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast
Screenshot 2024-02-04 at 2 04 43 AM
Screenshot 2024-02-04 at 2 05 11 AM
Screenshot 2024-02-04 at 9 05 36 PM
Screenshot 2024-02-04 at 9 05 55 PM
Screenshot 2024-02-04 at 9 06 10 PM
Screenshot 2024-02-04 at 9 06 22 PM
Screenshot 2024-02-04 at 9 06 32 PM
Screenshot 2024-02-04 at 9 06 43 PM

### CODE REVIEW

**Review by javalosr2004 — CHANGES_REQUESTED** [review]
I'm wondering if you could test out the API endpoints for GET and whenever you finish the admin endpoints for those as well. If you need access to mongodb, lmk, but a good way of testing if your route is working could be to first POST and then use GET, that way you don't need to first put sample data.

**Comment by SilveerDusk** [comment]
@javalosr2004 Can I get access to mongodb? I finished the rest of the api calls so they just need to be tested in the morning.

**Comment by SilveerDusk** [comment]
All API have now been tested on postman!

**Comment by SilveerDusk** [comment]
The merge conflicts are just from me installing chakra to make the UI work in my branch, so you can just keep the main version as my changes to the json files have nothing to do with the issues this pr resolves.

**Review by javalosr2004 — APPROVED** [review]
Everything looks amazing, nice error checking and making sure that only properties that are available are used in the PATCH endpoint.

**Pull request merged**
