### PR TITLE
Han event expanded view component issue 11

### LINKED ISSUE #11: Create Event Expanded View Component
**Description**
Create the event expanded view component as in the image below. 

**There should also be a sign up button somewhere in the component. 
The edit and delete buttons should be conditional, meaning that they are only visible if it is an admin logged in.**

**Acceptance Criteria**
- The component should look like the image below. 
- There should be a sign up button.
- Edit and delete buttons should be conditional
**This should be mobile friendly as well.**

Steps:
- Make the component
- Make sure its mobile friendly!!

**Additional Information**
Screenshot 2024-01-19 205221

### PR DESCRIPTION
**Pull request by HanYu-Wu04**
## Developer: HanYu Wu

Closes #11 
### Pull Request Summary

Created expanded view client component and its parent component which serves as a mock data setup to showcase the EventExpandedView Component. toggleModal function is created for better modal control, content section is conditionally rendered to appear only when showExpandedView is true, which happens when clicking on the expanded icon, collapsing when clicking on the X. Sign up options, edit, and delete feature are also conditionally rendered based on the user state, everything are styled for better mobile-friendliness by utilizing Chakra UI's responsive utility.

### Modifications

Added a ExpandedViewComponent.tsx, YourParentComponent.tsx, added ChakraProvider in Providers.tsx

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [x] Assign reviewers

### Screenshots/Screencast
Screen Shot 2024-01-27 at 4 53 48 PM
Screen Shot 2024-01-27 at 4 53 56 PM
Screen Shot 2024-01-27 at 4 54 07 PM

### CODE REVIEW

**Review by javalosr2004 — CHANGES_REQUESTED** [review]
When I tried the demo with <YourParentComponent/>, the css stylings started overlapping on lower resolutions.
image

**Review by javalosr2004 — CHANGES_REQUESTED** [review]
Nice job on fixing the media query for medium screen view ports, however, the overlap continues to show on smaller viewports, I went ahead and fixed this, I believe you will have to run `git pull` in order to see the changes, but can you make it so that the buttons are a little bigger on viewport `sm`.
image

**Comment by HanYu-Wu04** [comment]
Screen Shot 2024-01-28 at 3 09 06 PM

I think now it looks better in small viewports, let me know if there is any adjustment you felt needed.

**Review by javalosr2004 — CHANGES_REQUESTED** [review]
I don't think those changes were pushed.

**Comment by HanYu-Wu04** [comment]
My bad, I think now it's all pushed.

**Review by javalosr2004 — CHANGES_REQUESTED** [review]
There appears to be some overlap on the smallest viewport, thanks for fixing the other issue. Also, if you have the time, can you make the component expand not only when the icon is clicked but also when any part of the button (should just be replacing onClick or wrapping existing function to outer button).
image

**Review by javalosr2004 — APPROVED** [review]

**Review by javalosr2004 — CHANGES_REQUESTED** [review]
Bugs:
- if you click on the edit or delete or any of the buttons within the modal, it closes the modal and does the operation after opening it again. 
Improvements:
- Can you separate the eventDetails.startTime.toLocaleTimeString, to a seperate const variable within the Page itself. possibly as multiple variables.

**Review by javalosr2004 — CHANGES_REQUESTED** [review]
I went ahead and fixed a cursor pointer bug you had, if you want to run git pull, but I see you created an event props, and while I appreciate the effort, there is a premade / updated one in the database folder.

**Comment by javalosr2004** [comment]
make sure to run git pull origin main, to stay up to date with changes, after you run git pull

**Review by javalosr2004 — APPROVED** [review]
Amazing work Han! Your hard work has paid off! Time to merge!

**Pull request merged**
